### ISSUE TITLE
results with too many articles don't show 

### ISSUE THREAD

**Issue by darkbtf** [MrOrz/rumors-line-bot#3]
![](http://i.imgur.com/d93ciyP.jpg)![](http://i.imgur.com/k4Aeeza.jpg)

**Comment by MrOrz** [comment]
他會觸發 invalid token @@ 超怪
我來看看

**Comment by MrOrz** [comment]
Fixed by https://github.com/MrOrz/rumors-line-bot/commit/dd0138d15fdcc6c9b5d79549042878c5a06acd01
